name: tech_challenge_rt_cicd

on:
  push:
    branches: [ "main", "git_actions", "linting" ]
  pull_request:
    branches: [ "main", "git_actions" ]

jobs:

  # run linting only on clang for now
  tidy:
    name: Lint clang tidy
    runs-on: ubuntu-latest
    if: matrix.profile == 'profiles/ubuntu-clang'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Ensure clang-tidy is installed
        run: sudo apt-get install -y clang-tidy

      - name: Run clang-tidy
        run: |
          bash run_conan_clang_wclang_tidy.sh

  enforceformat:
    name: Enforce code formatting
    runs-on: ubuntu-latest
    if: matrix.profile == 'profiles/ubuntu-clang'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Ensure clang-format is installed
        run: sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          bash run_conan_clang_checkFormat.sh


  build-and-test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # If one fails, let the others finish
      matrix:
        include:
          - name: "Ubuntu (GCC)"
            os: ubuntu-latest
            profile: "profiles/ubuntu-gcc"
          - name: "Ubuntu (Clang)"
            os: ubuntu-latest
            profile: "profiles/ubuntu-clang"
          - name: "Windows (MSVC)"
            os: windows-latest
            profile: "profiles/windows-msvc"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      #- name: Set up Python
      #  uses: actions/setup-python@v5
      #  with:
      #     python-version: "3.12"
      - name: Install Conan
        run: pip install conan

      - name: Detect Conan profile
        run: conan profile detect --force

      - name: Install dependencies (Linux)
        if: matrix.profile == 'profiles/ubuntu-clang'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build clang


      - name: Build and Test Ubuntu Clang 
        if: matrix.profile == 'profiles/ubuntu-clang'
        run: |
          bash run_conan_clang.sh

      - name: Build and Test Ubuntu GCC
        if: matrix.profile == 'profiles/ubuntu-gcc'
        run: bash run_conan_gcc.sh

      - name: Setup MSVC Environment
        if: matrix.profile == 'profiles/windows-msvc'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build and Test Windows MSVC
        if: matrix.profile == 'profiles/windows-msvc'
        shell: cmd
        run: run_conan.bat

      - name: Package with CPack
        run: cmake --build --preset conan-release --target package
      
      - name: Upload CPack artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cpack-${{ matrix.name }}
          path: |
            build/**/*.tar.gz
            build/**/*.zip

  
      

